GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/640fcc3c5d5da3a8617dc043

###
PUT http://localhost:3001/api/notes/640fcc3c5d5da3a8617dc043
Content-Type: application/json

{
    "content": "This",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/640ff24b5e1b107f7d42e487

###
GET http://localhost:3001/api/notes/5c41c90e84d891c15dfa3431

###
PUT http://localhost:3001/api/notes/5c41c90e84d891c15dfa3431
Content-Type: application/json

{
    "content": "This note does not exist",
    "important": true
}

###
GET http://localhost:3001/api/notes/1

